/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "impresion.h"

void *
imprimir_1_svc(entrada arg1,  struct svc_req *rqstp)
{
	static char * result;
	printf("asdfi");

	// Comprobar la operación
	if (arg1.operacion == 0) {
		printf("%s REGISTER %s", arg1.user, arg1.datetime);
	} else if (arg1.operacion == 1) {
		printf("%s UNREGISTER %s", arg1.user, arg1.datetime);
	} else {
		printf("Los datos no están en el formato esperado");
	}

	return (void *) &result;
}
