/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "impresion.h"

bool_t
xdr_entrada (XDR *xdrs, entrada *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->operacion))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->datetime, 20))
		 return FALSE;
	return TRUE;
}
